require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - ".git/**/*"
    - "bin/*"
    - "*.gemspec"
    - "Gemfile*"
    - "lib/deadfinder/runner.rb"
    - "examples/**/*"
    - "vendor/bundle/**/*" # Add this line to exclude vendor/bundle directory
  SuggestExtensions: false

Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Exclude:
    - "lib/deadfinder.rb"
    - "lib/deadfinder/logger.rb"
    - "lib/deadfinder/utils.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/deadfinder.rb"
    - "lib/deadfinder/utils.rb"
    - "lib/deadfinder/runner.rb"
  Max: 150

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/deadfinder.rb"
    - "lib/deadfinder/runner.rb"
  Max: 30

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/deadfinder.rb"
    - "lib/deadfinder/runner.rb"
  Max: 30

Lint/SuppressedException:
  Exclude:
    - "lib/deadfinder.rb"
    - "lib/deadfinder/runner.rb"

Security/Open:
  Exclude:
    - "lib/deadfinder.rb"
    - "lib/deadfinder/runner.rb"

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 200
