source 'https://rubygems.org'

gem 'colorize'
gem 'concurrent-ruby-edge'
gem 'json'
gem 'nokogiri'
gem 'open-uri', '>= 0.4.0'
gem 'set'
gem 'sitemap-parser'
gem 'thor'
gem 'rspec'
gem 'yaml'
gem 'csv'
gem 'logger'

group :development, :test do
  gem 'rubocop', '1.72.2'
  gem 'rubocop-rspec'
  gem 'rubocop-rake'
  gem 'webmock', '~> 3.14'
  gem 'rake'
  gem 'simplecov'
  gem 'simplecov-cobertura'
  gem 'panolint'
end